In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"bikebuyer1.csv")

In [3]:
df.isnull().any()

ID                   True
Marital Status       True
Gender               True
Yearly Income       False
Children             True
Education           False
Occupation          False
Home Owner          False
Cars                False
Commute Distance     True
Region              False
Age                 False
Bike Buyer          False
dtype: bool

In [4]:
df['Marital Status'].fillna(df['Marital Status'].mode()[0],inplace=True)
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)
df['Children'].fillna(df['Children'].mode()[0],inplace=True)
df['Commute Distance'].fillna(df['Commute Distance'].mean(),inplace=True)
df['ID'].fillna(df['ID'].mean(),inplace=True)

In [5]:
df.head(4)
df['Marital Status'].unique()

array(['Single', 'Married'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Marital Status']=le.fit_transform(df['Marital Status'])

In [7]:
df['Gender']=le.fit_transform(df['Gender'])
df['Education']=le.fit_transform(df['Education'])
df['Occupation']=le.fit_transform(df['Occupation'])
df['Region']=le.fit_transform(df['Region'])
df['Bike Buyer']=le.fit_transform(df['Bike Buyer'])
df['Home Owner']=le.fit_transform(df['Home Owner'])

In [8]:
df.head(3)

ID  Marital Status  Gender  Yearly Income  Children  Education  \
0  22711.000000               1       1          30000       0.0          3   
1  13555.000000               0       0          40000       0.0          1   
2  17744.435249               0       1         160000       5.0          3   

   Occupation  Home Owner  Cars  Commute Distance  Region  Age  Bike Buyer  
0           0           0     1               1.0       0   33           1  
1           0           1     0               1.0       0   37           1  
2           3           0     3               2.0       0   55           0

In [9]:
x=df.iloc[:,1:5].values
z=df.iloc[:,6:12].values
y=df.iloc[:,12:13].values
x=np.concatenate((x,z),axis=1)

In [10]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()


In [11]:
p=one.fit_transform(x[:,4:5]).toarray()

C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [12]:
q=one.fit_transform(x[:,8:9]).toarray()

C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [13]:
x=np.delete(x,4,axis=1)
x=np.delete(x,8,axis=1)

In [14]:
x=np.concatenate((p,x),axis=1)
x=np.concatenate((q,x),axis=1)

In [15]:
x

array([[1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 3., 2., 0.],
       ...,
       [1., 0., 0., ..., 2., 1., 0.],
       [1., 0., 0., ..., 3., 1., 0.],
       [1., 0., 0., ..., 3., 2., 0.]])

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [28]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion="entropy",random_state=0)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [19]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [20]:
ydtc=dtc.predict(x_test)

In [21]:
ydtc

array([0, 0, 0, ..., 1, 0, 0])

In [22]:
y_test

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [25]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,ydtc)

In [26]:
acc

0.83