In [2]:
# import the libraries
import pandas as pd
import numpy as np

In [3]:
#step2 - Reading the dataset
dataset = pd.read_csv("Churn_Modelling.csv")

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender             False
Age                 True
Tenure             False
Balance             True
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [6]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225     Spain  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850     Spain  Female  43.0   
5          6    15574012       Chu          645     Spain    Male  44.0   
6          7    15592531  Bartlett          822       NaN    Male  50.0   
7          8    15656148    Obinna          376   Germany  Female  29.0   
8          9    15792365        He          501    France    Male  44.0   
9         10    15592389        H?          684    France    Male   NaN   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [7]:
dataset['Geography'].fillna(dataset['Geography'].mode()[0],inplace = True)
dataset['Age'].fillna(dataset['Age'].mean(),inplace = True)
dataset['Balance'].fillna(dataset['Balance'].median(),inplace = True)

In [8]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [9]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender        Age  \
0          1    15634602  Hargrave          619    France  Female  42.000000   
1          2    15647311      Hill          225     Spain  Female  41.000000   
2          3    15619304      Onio          629    France  Female  42.000000   
3          4    15701354      Boni          699    France  Female  39.000000   
4          5    15737888  Mitchell          850     Spain  Female  43.000000   
5          6    15574012       Chu          645     Spain    Male  44.000000   
6          7    15592531  Bartlett          822    France    Male  50.000000   
7          8    15656148    Obinna          376   Germany  Female  29.000000   
8          9    15792365        He          501    France    Male  44.000000   
9         10    15592389        H?          684    France    Male  38.922992   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [10]:
p = dataset['Geography'].mode()

In [11]:
p

0    France
dtype: object

In [12]:
p[0]

'France'

In [13]:
dataset['Geography'].mode()[0]

'France'

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Geography'] = le.fit_transform(dataset['Geography'])
# - 0 --some
# - 1 some 
# - 2 somee


In [15]:
dataset['Gender'] = le.fit_transform(dataset['Gender'])

#mee - 1
#female -0



In [16]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender        Age  \
0          1    15634602  Hargrave          619          0       0  42.000000   
1          2    15647311      Hill          225          2       0  41.000000   
2          3    15619304      Onio          629          0       0  42.000000   
3          4    15701354      Boni          699          0       0  39.000000   
4          5    15737888  Mitchell          850          2       0  43.000000   
5          6    15574012       Chu          645          2       1  44.000000   
6          7    15592531  Bartlett          822          0       1  50.000000   
7          8    15656148    Obinna          376          1       0  29.000000   
8          9    15792365        He          501          0       1  44.000000   
9         10    15592389        H?          684          0       1  38.922992   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [17]:
x = dataset.iloc[:,3:13].values

In [18]:
y = dataset.iloc[:,13].values

In [19]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [21]:
type(y)

numpy.ndarray

In [22]:
x.shape

(10000, 10)

In [23]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,1:2]).toarray()






C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [24]:
x = np.delete(x,1,axis = 1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [25]:
x = np.concatenate((z,x),axis = 1)

In [26]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
x.shape

(10000, 12)

In [28]:
y.shape

(10000,)

In [29]:
#split the data in to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [30]:
x_test.shape

(2000, 12)

In [31]:
y_test.shape 

(2000,)

In [32]:
x_train.shape 

(8000, 12)

In [33]:
y_train.shape

(8000,)

In [34]:
x_train[:,5:10]

array([[3.4000000e+01, 5.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.2000000e+01, 1.0000000e+00, 7.5681520e+04, 1.0000000e+00,
        1.0000000e+00],
       [2.9000000e+01, 2.0000000e+00, 1.1236734e+05, 1.0000000e+00,
        1.0000000e+00],
       ...,
       [3.5000000e+01, 5.0000000e+00, 1.6127405e+05, 2.0000000e+00,
        1.0000000e+00],
       [3.8000000e+01, 9.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.8000000e+01, 1.0000000e+00, 1.0807633e+05, 1.0000000e+00,
        1.0000000e+00]])

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [36]:
x_train.shape

(8000, 12)

In [37]:
import keras
from keras.layers import Dense
from keras.models import Sequential


Using TensorFlow backend.


In [38]:
model = Sequential()

In [39]:
model.add(Dense(units = 12,init ="random_uniform",activation="relu" ))

C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [40]:
keras.__version__

'2.3.1'