In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv(r"churn_modelling.csv")

In [6]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225     Spain  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [7]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender             False
Age                 True
Tenure             False
Balance             True
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [11]:
df['Geography'].fillna(df['Geography'].mode()[0],inplace=True)

In [12]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                 True
Tenure             False
Balance             True
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [13]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

In [14]:
df['Balance'].fillna(df['Balance'].median(),inplace=True)

In [16]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [24]:
df['Geography']=le.fit_transform(df['Geography'])
df['Gender']=le.fit_transform(df['Gender'])

In [25]:
df

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender   Age  \
0             1    15634602   Hargrave          619          0       0  42.0   
1             2    15647311       Hill          225          2       0  41.0   
2             3    15619304       Onio          629          0       0  42.0   
3             4    15701354       Boni          699          0       0  39.0   
4             5    15737888   Mitchell          850          2       0  43.0   
...         ...         ...        ...          ...        ...     ...   ...   
9995       9996    15606229   Obijiaku          771          0       1  39.0   
9996       9997    15569892  Johnstone          516          0       1  35.0   
9997       9998    15584532        Liu          709          0       0  36.0   
9998       9999    15682355  Sabbatini          772          1       1  42.0   
9999      10000    15628319     Walker          792          0       0  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [26]:
df.corr()

RowNumber  CustomerId  CreditScore  Geography    Gender  \
RowNumber         1.000000    0.004202     0.006294  -0.010358  0.018196   
CustomerId        0.004202    1.000000     0.005413   0.006516 -0.002641   
CreditScore       0.006294    0.005413     1.000000   0.007163 -0.002564   
Geography        -0.010358    0.006516     0.007163   1.000000  0.004719   
Gender            0.018196   -0.002641    -0.002564   0.004719  1.000000   
Age               0.000586    0.009342    -0.003962   0.022710 -0.027442   
Tenure           -0.006495   -0.014883     0.001526   0.003739  0.014733   
Balance          -0.009053   -0.012427     0.006401   0.069415  0.012080   
NumOfProducts     0.007246    0.016972     0.012920   0.003972 -0.021859   
HasCrCard         0.000599   -0.014025    -0.004756  -0.008523  0.005766   
IsActiveMember    0.012044    0.001665     0.025110   0.006724  0.022544   
EstimatedSalary  -0.005988    0.015271    -0.001437  -0.001369 -0.008112   
Exited           -0.016571   -0.006248    -0.026611   0.035943 -0.106512   

                      Age    Tenure   Balance  NumOfProducts  HasCrCard  \
RowNumber        0.000586 -0.006495 -0.009053       0.007246   0.000599   
CustomerId       0.009342 -0.014883 -0.012427       0.016972  -0.014025   
CreditScore     -0.003962  0.001526  0.006401       0.012920  -0.004756   
Geography        0.022710  0.003739  0.069415       0.003972  -0.008523   
Gender          -0.027442  0.014733  0.012080      -0.021859   0.005766   
Age              1.000000 -0.010116  0.028422      -0.030786  -0.011648   
Tenure          -0.010116  1.000000 -0.012257       0.013444   0.022583   
Balance          0.028422 -0.012257  1.000000      -0.304187  -0.014846   
NumOfProducts   -0.030786  0.013444 -0.304187       1.000000   0.003183   
HasCrCard       -0.011648  0.022583 -0.014846       0.003183   1.000000   
IsActiveMember   0.085588 -0.028362 -0.010076       0.009612  -0.011866   
EstimatedSalary -0.007258  0.007784  0.012800       0.014204  -0.009933   
Exited           0.285284 -0.014001  0.118537      -0.047820  -0.007138   

                 IsActiveMember  EstimatedSalary    Exited  
RowNumber              0.012044        -0.005988 -0.016571  
CustomerId             0.001665         0.015271 -0.006248  
CreditScore            0.025110        -0.001437 -0.026611  
Geography              0.006724        -0.001369  0.035943  
Gender                 0.022544        -0.008112 -0.106512  
Age                    0.085588        -0.007258  0.285284  
Tenure                -0.028362         0.007784 -0.014001  
Balance               -0.010076         0.012800  0.118537  
NumOfProducts          0.009612         0.014204 -0.047820  
HasCrCard             -0.011866        -0.009933 -0.007138  
IsActiveMember         1.000000        -0.011421 -0.156128  
EstimatedSalary       -0.011421         1.000000  0.012097  
Exited                -0.156128         0.012097  1.000000

In [36]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()

In [44]:
x=np.array(df.iloc[:,3:13])
y=np.array(df.iloc[:,13:14])

In [45]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [46]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [49]:
z=one.fit_transform(x[:,1:2]).toarray()

C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [50]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [54]:
x=np.delete(x,1,axis=1)

In [55]:
x=np.concatenate((z,x),axis=1)

In [56]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [58]:
x.shape

(10000, 12)