In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"fish.csv")

In [3]:
dataset['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()

In [5]:
dataset["Species"]=le.fit_transform(dataset["Species"])

In [6]:
z=dataset.iloc[:,0:1].values
x=dataset.iloc[:,2:].values
y=dataset.iloc[:,1:2].values

In [7]:
x=np.concatenate((z,x),axis=1)

In [8]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()

In [9]:
p=one.fit_transform(x[:,0:1]).toarray()

C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [10]:
x.shape

(159, 6)

In [11]:
x=np.delete(x,0,axis=1)

In [12]:
p

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [13]:
x=np.concatenate((p,x),axis=1)

In [14]:
x.shape

(159, 12)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
y_pred=lr.predict(x_test)

In [18]:
from sklearn.metrics import r2_score
acc=r2_score(y_test,lr.predict(x_test))

In [19]:
acc

0.910235031620258

In [20]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(random_state=0)

In [21]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [22]:
ydtr=dtr.predict(x_test)

In [23]:
ydtr

array([ 430. ,  110. ,  145. ,  145. ,  514. , 1015. ,  685. ,  345. ,
        950. ,  110. ,  345. ,  500. ,  820. , 1100. ,   51.5,   87. ,
        150. , 1550. ,  110. ,  725. ,   51.5,  500. ,  130. , 1550. ,
         69. ,  450. ,  725. ,  300. , 1015. ,    8.7,  700. ,  120. ])

In [24]:
y_test

array([[ 390. ],
       [   0. ],
       [ 170. ],
       [ 160. ],
       [ 556. ],
       [ 900. ],
       [ 800. ],
       [ 300. ],
       [ 975. ],
       [ 115. ],
       [ 200. ],
       [ 456. ],
       [1000. ],
       [1000. ],
       [  60. ],
       [  78. ],
       [ 145. ],
       [1600. ],
       [ 130. ],
       [ 720. ],
       [  55. ],
       [ 390. ],
       [ 120. ],
       [1650. ],
       [  90. ],
       [ 450. ],
       [ 700. ],
       [ 270. ],
       [ 850. ],
       [   9.7],
       [ 650. ],
       [ 110. ]])

In [25]:
accdtr=r2_score(y_test,ydtr)

In [26]:
accdtr

0.9724345073124595

In [28]:
yd=dtr.predict([[1,0,0,0,0,0,0,1213,1235,1456,3214,256]])

In [29]:
yd

array([1550.])

In [30]:
from sklearn.ensemble import RandomForestRegressor
rdr=RandomForestRegressor()

In [31]:
rdr.fit(x_train,y_train)

C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Jyothi Swaroop\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [32]:
ydr=rdr.predict(x_test)

In [34]:
accrdr=r2_score(y_test,ydr)

In [35]:
accrdr

0.9487835646349508